@baseUrl = http://localhost:3001
@authToken = {{authenticate.response.body.access_token}}

###
# @name authenticate
POST  {{baseUrl}}/authenticate/create-session
Content-Type: application/json

{
  "email": "diogofaria128@gmail.com",
  "password": "fadababaca"
}


###
# @name create-patient
POST {{baseUrl}}/patients/create
Content-Type: application/json

{
  "name": "asdfasfdasfasfasfdasfd Carlos Rodriguies",
  "email": "ccccccccccc@gmail.com",
  "phone": "+55 11 99999-1528",
  "isActive": true
}

###
# @name update-patient
POST {{baseUrl}}/patients/update
Content-Type: application/json

{
  "id":"83a68441-ce31-49ec-a11c-65ee7c69c76a",
  "name": "RENATO2222 GARILHO ROMÁRIO",
  "email": "renato2_garilho@gmail.com",
  "phone": "+55 11 99999-1528",
  "isActive": true
}

###
# @name list-patients
GET {{baseUrl}}/patient/list-all
Authorization: Bearer {{authToken}}

###
# @name list-patient-by-email
POST  {{baseUrl}}/patient/list-by-email
Content-Type: application/json

{
  "email": "diogofaria073@gmail.com"
}

###

# @name delete-patient-by-id
DELETE   {{baseUrl}}/patient/delete/b145663c-df96-4ffc-a42e-1cebb9113393
Content-Type: application/json

###
# @name create-user
POST {{baseUrl}}/users/create
Content-Type: application/json

{
  "name": "Diogo Martins Almeida Faria",
  "email": "diogofaria128@gmail.com",
  "password": "fadababaca",
  "roles": ["ADMIN", "BASIC"]
}

###
# @name list-all-users
GET {{baseUrl}}/users/list-all
Content-Type: application/json


###
# @name list-user-by-id
GET   {{baseUrl}}/user/list-by-id/9a028549-1fe5-4d1b-9207-d99333cf93fe
Content-Type: application/json

###

# @name list-user-by-email
GET    {{baseUrl}}/user/list-by-email
Content-Type: application/json

{
  "email": "ronaldoLima.2222@gmail.com"
}

###
# @name delete-user-by-id
DELETE   {{baseUrl}}/user/delete/146ee11b-b598-49d8-9669-8c8af7ed49ba
Content-Type: application/json

