@baseUrl = http://localhost:3001
## @authToken = {{authenticate.response.body.access_token}}


###
# @name create-patient
POST {{baseUrl}}/patients/create
Content-Type: application/json

{
  "name": "asdfasfdasfasfasfdasfd Carlos Rodriguies",
  "email": "ccccccccccc@gmail.com",
  "phone": "+55 11 99999-1528",
  "isActive": true
}

###
# @name update-patient
POST {{baseUrl}}/patients/update
Content-Type: application/json

{
  "id":"83a68441-ce31-49ec-a11c-65ee7c69c76a",
  "name": "RENATO2222 GARILHO ROMÁRIO",
  "email": "renato2_garilho@gmail.com",
  "phone": "+55 11 99999-1528",
  "isActive": true
}

###
# @name list-patients
GET {{baseUrl}}/patient/list-all

###
# @name list-patient-by-email
POST  {{baseUrl}}/patient/list-by-email
Content-Type: application/json

{
  "email": "diogofaria073@gmail.com"
}

###

# @name delete-patient-by-id
DELETE   {{baseUrl}}/patient/delete/b145663c-df96-4ffc-a42e-1cebb9113393
Content-Type: application/json
