@baseUrl = http://localhost:3001
## @authToken = {{authenticate.response.body.access_token}}
###
# @name create-patient
POST {{baseUrl}}/patients/create
Content-Type: application/json

{
  "name": "asdfasfdasfasfasfdasfd Carlos Rodriguies",
  "email": "fffffasdfasdfasdfasfdasdfasdfasdfasdfasdf@gmail.com",
  "phone": "+55 11 99999-1528",
  "isActive": true
}

###
# @name list-patients
GET {{baseUrl}}/patient/list-all

###
# @name list-patient-by-email
POST  {{baseUrl}}/patient/list-by-email
Content-Type: application/json

{
  "email": "diogofaria073@gmail.com"
}

###

# @name list-patient-by-id
POST  {{baseUrl}}/patient/list-by-id
Content-Type: application/json

{
  "id": "e50e8913-4812-452d-bff7-55b28c3fa715"
}